onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /top_testbench/clk
add wave -noupdate /top_testbench/reset
add wave -noupdate /top_testbench/WriteData
add wave -noupdate /top_testbench/DataAdr
add wave -noupdate /top_testbench/MemWrite
add wave -noupdate /top_testbench/dut/dmem/clk
add wave -noupdate /top_testbench/dut/dmem/we
add wave -noupdate /top_testbench/dut/dmem/a
add wave -noupdate /top_testbench/dut/dmem/wd
add wave -noupdate /top_testbench/dut/dmem/rd
add wave -noupdate /top_testbench/dut/dmem/RAM
add wave -noupdate {/top_testbench/dut/dmem/RAM[63]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[62]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[61]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[60]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[59]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[58]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[57]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[56]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[55]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[54]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[53]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[52]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[51]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[50]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[49]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[48]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[47]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[46]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[45]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[44]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[43]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[42]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[41]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[40]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[39]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[38]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[37]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[36]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[35]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[34]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[33]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[32]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[31]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[30]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[29]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[28]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[27]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[26]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[25]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[24]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[23]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[22]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[21]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[20]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[19]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[18]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[17]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[16]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[15]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[14]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[13]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[12]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[11]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[10]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[9]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[8]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[7]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[6]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[5]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[4]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[3]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[2]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[1]}
add wave -noupdate {/top_testbench/dut/dmem/RAM[0]}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {111 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {1 ns}
